# Generated by Django 6.0.1 on 2026-01-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeoName",
            fields=[
                ("geonameid", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("asciiname", models.CharField(blank=True, max_length=200)),
                ("latitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("feature_class", models.CharField(db_index=True, max_length=1)),
                ("feature_code", models.CharField(db_index=True, max_length=10)),
                ("country_code", models.CharField(db_index=True, max_length=2)),
                ("admin1_code", models.CharField(blank=True, max_length=20)),
                ("population", models.BigIntegerField(db_index=True, default=0)),
                ("elevation", models.IntegerField(blank=True, null=True)),
                ("timezone", models.CharField(blank=True, max_length=40)),
                ("modification_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-population"],
                "indexes": [
                    models.Index(
                        fields=["country_code", "population"],
                        name="geodata_geo_country_8fe4ee_idx",
                    ),
                    models.Index(
                        fields=["name", "country_code"],
                        name="geodata_geo_name_b7edbc_idx",
                    ),
                ],
            },
        ),
    ]
