# Generated by Django 6.0.1 on 2026-01-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geodata", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="geoname",
            name="geodata_geo_country_8fe4ee_idx",
        ),
        migrations.RemoveIndex(
            model_name="geoname",
            name="geodata_geo_name_b7edbc_idx",
        ),
        migrations.AddIndex(
            model_name="geoname",
            index=models.Index(
                fields=["country_code", "-population"],
                name="geodata_geo_country_7aaba8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="geoname",
            index=models.Index(
                fields=["feature_class", "-population"],
                name="geodata_geo_feature_9a4df1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="geoname",
            index=models.Index(
                fields=["country_code", "feature_class", "-population"],
                name="geodata_geo_country_47cfe2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="geoname",
            index=models.Index(
                fields=["name", "-population"], name="geodata_geo_name_d2cf16_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="geoname",
            index=models.Index(
                fields=["asciiname"], name="geodata_geo_asciina_9b4848_idx"
            ),
        ),
    ]
